emotes = {
	"MOURN",
	"SNIFF",
	"LICK",
	"SNICKER",
	"GUFFAW",
	"GLOAT",
	"PITY",
	"VIOLIN",
	"BYE",
	"BITE",
	"CACKLE",
	"SHOO",
	"SLAP",
	"TEASE",
	"TAUNT",
	"MOCK",
	"MOO",
	"CHUCKLE",
	"BONK",
	"FLEX",
	"GRIN",
	"LAUGH",
	"MOON",
	"NO",
	"ROAR",
	"ROFL",
	"SCRATCH",
	"SIGH",
	"SNARL",
	"TAP",
	"INSULT",
	"BARK",
	"BECKON",
	"CALM",
	"CHICKEN",
	"COMFORT",
	"CUDDLE",
	"CURTSEY",
	"GIGGLE",
	"GROWL",
	"NOSEPICK",
	"RASP",
	"RUDE",
	"SMIRK",
	"SNUB",
	"SOOTHE",
	"THANK",
	"TICKLE",
	"VETO",
	"YAWN",
	--[["POUNCE",]]
	--[["CRACK",]]
	--[["AGREE",]]
	--[["AMAZE",]]
	--[["ANGRY",]]
	--[["APOLOGIZE",]]
	--[["APPLAUD",]]
	--[["BASHFUL",]]
	--[["BEG",]]
	--[["BLEED",]]
	--[["BLINK",]]
	--[["BLUSH",]]
	--[["COMMEND",]]
	--[["TRAIN",]]
	--[["RAISE",]]
	--[["INTRODUCE",]]
	--[["JK",]]
	--[["LISTEN",]]
	--[["TALK",]]
	--[["TALKEX",]]
	--[["TALKQ",]]
	--[["BORED",]]
	--[["BOUNCE",]]
	--[["BRB",]]
	--[["BOW",]]
	--[["BURP",]]
	--[["CHEER",]]
	--[["CLAP",]]
	--[["CONFUSED",]]
	--[["CONGRATULATE",]]
	--[["UNUSED",]]
	--[["COUGH",]]
	--[["COWER",]]
	--[["CRINGE",]]
	--[["CRY",]]
	--[["CURIOUS",]]
	--[["DANCE",]]
	--[["DRINK",]]
	--[["DROOL",]]
	--[["EAT",]]
	--[["EYE",]]
	--[["FART",]]
	--[["FIDGET",]]
	--[["FROWN",]]
	--[["GASP",]]
	--[["GAZE",]]
	--[["GLARE",]]
	--[["GREET",]]
	--[["GROAN",]]
	--[["GROVEL",]]
	--[["HAIL",]]
	--[["HAPPY",]]
	--[["HELLO",]]
	--[["HUG",]]
	--[["HUNGRY",]]
	--[["KISS",]]
	--[["KNEEL",]]
	--[["LAYDOWN",]]
	--[["MASSAGE",]]
	--[["MOAN",]]
	--[["NOD",]]
	--[["PANIC",]]
	--[["PEER",]]
	--[["PLEAD",]]
	--[["POINT",]]
	--[["POKE",]]
	--[["PRAY",]]
	--[["SALUTE",]]
	--[["SEXY",]]
	--[["SHAKE",]]
	--[["SHOUT",]]
	--[["SHRUG",]]
	--[["SHY",]]
	--[["SIT",]]
	--[["SLEEP",]]
	--[["SPIT",]]
	--[["STARE",]]
	--[["SURPRISED",]]
	--[["SURRENDER",]]
	--[["THREATEN",]]
	--[["TIRED",]]
	--[["VICTORY",]]
	--[["WAVE",]]
	--[["WELCOME",]]
	--[["WHINE",]]
	--[["WHISTLE",]]
	--[["WORK",]]
	--[["BOGGLE",]]
	--[["COLD",]]
	--[["DUCK",]]
	--[["LOST",]]
	--[["PONDER",]]
	--[["PRAISE",]]
	--[["PURR",]]
	--[["PUZZLE",]]
	--[["READY",]]
	--[["SHIMMY",]]
	--[["SHIVER",]]
	--[["STINK",]]
	--[["THIRSTY",]]
	--[["STAND",]]
	--[["SMILE",]]
	--[["SCARED",]]
	--[["FLOP",]]
	--[["LOVE",]]
}